package grammar

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"luna/internal/highlight"
)

// The banner every generated file carries. Editing one by hand is the failure this package
// exists to prevent, and TestGeneratedFilesAreCurrent is what makes the warning true.
const (
	bannerLine1 = "DO NOT EDIT. Generated by cmd/gengrammar from lexer.md §0."
	bannerLine2 = "Run `go run ./cmd/gengrammar` after any ruling that touches the token table."
)

// TmLanguage is the VSCode grammar, tmLanguage JSON.
func (g *Grammar) TmLanguage() ([]byte, error) {
	// The tmLanguage schema has nowhere for a comment, so the banner rides in as a key. It
	// sorts to the front of the object because encoding/json orders map keys — but this is a
	// struct field, so its position is the struct's.
	doc := struct {
		Comment string `json:"_generated"`
		*Grammar
	}{Comment: bannerLine1 + " " + bannerLine2, Grammar: g}

	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	enc.SetIndent("", "  ")
	// Without this every `<` and `>` in a pattern becomes < — RANGE_EXCL is `\.\.<` and
	// ARROW is `->`, so the file would be correct, unreadable, and impossible to review.
	enc.SetEscapeHTML(false)
	if err := enc.Encode(doc); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// ShikiTS is the same grammar as a TypeScript module.
//
// Shiki accepts a grammar structurally, so the object is the tmLanguage verbatim — JSON is
// a subset of TS object syntax and needs no translation.
//
// The type declares _generated alongside the five real fields. TypeScript's excess property
// check rejects an object literal carrying a key its annotation does not name, so omitting
// it would make the file a compile error on any site that actually type-checks — which is
// the one failure mode nothing in this repo can catch, there being no tsc here.
func (g *Grammar) ShikiTS() ([]byte, error) {
	body, err := g.TmLanguage()
	if err != nil {
		return nil, err
	}

	var b strings.Builder
	fmt.Fprintf(&b, `/**
 * Luna syntax highlighting for Shiki.
 *
 * %s
 * %s
 *
 * SETUP:   npm i -D shiki        (type-only dep; Astro ships the runtime)
 * WIRING:  markdown.shikiConfig.langs: [lunaGrammar] in astro.config.mjs,
 *          then luna-labelled code fences highlight.
 *
 * The oracle is the authority here, not this file: patterns come from §0's table,
 * attempt order from its row order, and keyword grouping from internal/highlight,
 * so a ruling that moves a row moves this too. For documentation built from the
 * repo, prefer cmd/highlight — it runs the real lexer and needs no grammar at all.
 *
 * The type is declared locally rather than imported from shiki: this repo has no
 * node_modules, so the import would be a permanent unresolved reference (R59).
 */

export type LunaGrammar = {
  _generated: string;
  name: string;
  scopeName: string;
  fileTypes: string[];
  patterns: unknown[];
  repository: Record<string, unknown>;
};

export const lunaGrammar: LunaGrammar = `, bannerLine1, bannerLine2)

	b.Write(bytes.TrimRight(body, "\n"))
	b.WriteString(";\n")
	return []byte(b.String()), nil
}

// treeSitterCaptures maps highlight's classes to tree-sitter's capture vocabulary, which is
// a third naming scheme again — Zed and Neovim key on these, not on TextMate scopes.
var treeSitterCaptures = map[string]string{
	"tok-decl":  "@keyword",
	"tok-kw":    "@keyword.control",
	"tok-const": "@constant.builtin",
	"tok-var":   "@variable.builtin",
}

// nodeCaptures are grammar.js's node types and the capture each takes, in emission order.
//
// Every one is gated on the *committed* parser producing it — see HighlightsSCM.
var nodeCaptures = []struct{ node, capture string }{
	{"comment", "@comment"},
	{"string", "@string"},
	{"command", "@string.special"},
	{"regex", "@string.regexp"},
	{"attribute", "@attribute"},
	{"number", "@number"},
	{"punctuation", "@operator"},
}

// HighlightsSCM is the tree-sitter query file Zed reads.
//
// Only the vocabulary is generated. The node captures name grammar.js's own node types, and
// grammar.js stays hand-written because changing it means regenerating parser.c through the
// container — see tooling/generate-grammar.sh.
//
// That two-step is why `have` exists. A query naming a node type the parser does not produce
// does not degrade gracefully: tree-sitter fails the whole query with TSQueryErrorNodeType,
// and Zed loses highlighting for the language entirely — not just for that pattern. So a
// capture is emitted only once src/node-types.json says the committed parser can produce it.
//
// The sequencing falls out of that. Adding a rule to grammar.js changes nothing here; running
// generate-grammar.sh updates node-types.json, which makes this file stale, which fails
// TestGeneratedFilesAreCurrent and asks for one more gengrammar run. The query can never
// reference a node ahead of the parser, and it picks the node up as soon as it exists.
func (g *Grammar) HighlightsSCM(p *patterns, have map[string]bool) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "; %s\n; %s\n;\n", bannerLine1, bannerLine2)
	b.WriteString("; Keyword classification via #match? predicates: grammar.js is deliberately\n")
	b.WriteString("; lexical and emits every word as (identifier), leaving the split to here.\n")
	b.WriteString("; Node captures track src/node-types.json, so this file never names a node\n")
	b.WriteString("; the committed parser cannot produce.\n\n")

	for _, nc := range nodeCaptures {
		if have[nc.node] {
			fmt.Fprintf(&b, "(%s) %s\n", nc.node, nc.capture)
		}
	}
	b.WriteString("\n")

	groups := keywordLexemes(p)
	classes := make([]string, 0, len(groups))
	for c := range groups {
		classes = append(classes, c)
	}
	sort.Strings(classes)

	for _, c := range classes {
		capture := treeSitterCaptures[c]
		fmt.Fprintf(&b, "((identifier) %s\n (#match? %s \"^(%s)$\"))\n\n",
			capture, capture, strings.Join(groups[c], "|"))
	}

	fmt.Fprintf(&b, "((identifier) @type\n (#match? @type \"^(%s)$\"))\n\n",
		strings.Join(highlightedTypes(p), "|"))
	b.WriteString("((identifier) @variable\n (#match? @variable \"^_$\"))\n")

	return []byte(b.String())
}

// keywordLexemes buckets §0's keyword lexemes by highlight's class, for the query file.
//
// A #match? predicate tests one (identifier) node, so a lexeme containing a space cannot be
// expressed: `yield from` is one token to the lexer (R223) and two identifiers to
// tree-sitter. It is dropped, which leaves `yield` coloured and `from` bare — the same
// degradation the hand-written file had, now deliberate rather than incidental. `match!`
// survives because grammar.js's identifier rule admits a trailing `!`.
func keywordLexemes(p *patterns) map[string][]string {
	out := map[string][]string{}
	for _, name := range p.namesInOrder("keyword", nil) {
		lex := p.lexeme(name)
		if lex == "" || strings.ContainsAny(lex, " \t") {
			continue
		}
		class := highlight.Class(kindByName(name))
		if _, ok := treeSitterCaptures[class]; !ok {
			panic(fmt.Sprintf("grammar: keyword %s has class %q with no tree-sitter capture", name, class))
		}
		out[class] = append(out[class], lex)
	}
	return out
}
