; DO NOT EDIT. Generated by cmd/gengrammar from lexer.md §0.
; Run `go run ./cmd/gengrammar` after any ruling that touches the token table.
;
; Keyword classification via #match? predicates: grammar.js is deliberately
; lexical and emits every word as (identifier), leaving the split to here.
; Node captures track src/node-types.json, so this file never names a node
; the committed parser cannot produce.

(comment) @comment
(string) @string
(command) @string.special
(regex) @string.regexp
(attribute) @attribute
(number) @number
(punctuation) @operator

((identifier) @constant.builtin
 (#match? @constant.builtin "^(true|false|null|undefined|nan|inf)$"))

((identifier) @keyword
 (#match? @keyword "^(var|let|const|fn|gen|constraint|proto|enum|error|capability|attribute|test|export|import)$"))

((identifier) @keyword.control
 (#match? @keyword.control "^(if|else|foreach|in|while|break|continue|return|yield|match!|match|where|defer|by|try|catch|throw|copy|spawn|await|comptime|comptype|is|as|apply|declared|use)$"))

((identifier) @variable.builtin
 (#match? @variable.builtin "^(self)$"))

((identifier) @type
 (#match? @type "^(any|bool|byte|bytes|command|double|duration|float|instant|int|list|never|promise|regex|secret|sink|stream|string|stringBuilder|table|type)$"))

((identifier) @variable
 (#match? @variable "^_$"))
