/**
 * tree-sitter-luna: a HIGHLIGHTING-GRADE grammar, deliberately lexical.
 *
 * DO NOT EDIT. Generated by cmd/gengrammar from lexer.md §0.
 * Run `go run ./cmd/gengrammar` after any ruling that touches the token table.
 *
 * This is not the Luna parser (that is the compiler's job, per the spec's grammar
 * pins); it tokenizes accurately and imposes almost no structure, so it never
 * mis-parses valid code and never breaks highlighting on partial code while typing.
 * Keyword classification happens in highlights.scm via #match? predicates.
 *
 * AFTER REGENERATING: run tooling/generate-grammar.sh, which regenerates src/ from
 * this file and then runs gengrammar again so highlights.scm can pick up any new
 * node type. Until it does, the checked-in parser.c still implements the previous
 * version and nothing here takes effect — src/ is what Zed compiles, not this.
 */
module.exports = grammar({
  name: 'luna',

  extras: $ => [/\s/, $.comment],

  rules: {
    source_file: $ => repeat($._token),

    _token: $ => choice(
      $.attribute,
      $.regex,
      $.string,
      $.command,
      $.number,
      $.identifier,
      $.punctuation,
    ),

    comment: _ => token(choice(
      /\/\/[^\n]*/,
      /\/\*[^*]*\*+([^/*][^*]*\*+)*\//,
    )),

    attribute: _ => token(/#\[[^\]]*\]/),

    regex: _ => token(/~"[^"\\]*(?:\\[\s\S][^"\\]*)*"[imsxb]*/),

    string: _ => token(choice(
      /"""([^"\\]|\\[\s\S]|"[^"\\]|""[^"\\])*"""/,
      /'''([^']|'[^']|''[^'])*'''/,
      /b?"[^"\\\n]*(?:\\[^\n][^"\\\n]*)*"/,
      /b?'[^'\\\n]*(?:\\[^\n][^'\\\n]*)*'/,
    )),

    command: _ => token(/`[^`\\\n]*(?:\\[^\n][^`\\\n]*)*`/),

    number: _ => token(/(?:0|[1-9](?:_?[0-9])*)\.[0-9](?:_?[0-9])*(?:[eE][+-]?[0-9]+)?|(?:0|[1-9](?:_?[0-9])*)[eE][+-]?[0-9]+|0x[0-9a-fA-F](?:_?[0-9a-fA-F])*|0b[01](?:_?[01])*|0o[0-7](?:_?[0-7])*|0|[1-9](?:_?[0-9])*/),

    identifier: _ => token(/[A-Za-z_][A-Za-z0-9_]*!?/),

    punctuation: _ => token(/\?\?\?=|\?\?\?|\?\?=|\?\?|\?->|\?\.|\?|\.\.\.|\.\.<|\.\.|\.|\x7c\x7c|\x7c|&&|&|->|-=|-|=>|==|=|!=|!|<=|<|>=|>|\+=|\+|\*=|\*|\/=|\/|%=|%|@@|@|\(|\)|\{|\}|\[|\]|,|;|:|~/),
  },
});
