#!/usr/bin/env bash
#
# publish-grammar.sh: commit the regenerated grammar, push, and repoint
# zed-luna's extension.toml at the new revision (then commit and push that
# too). Run after tooling/generate-grammar.sh. Run from anywhere in the repo.

set -euo pipefail
root="$(git -C "$(cd "$(dirname "$0")" && pwd)" rev-parse --show-toplevel)"
cd "$root"

GRAMMAR="tooling/tree-sitter-luna"
EXT="tooling/zed-luna"

# 1) Commit the grammar (if generation actually changed anything) and push, so
#    the rev we pin exists remotely. An unchanged grammar is NORMAL (a fresh
#    machine regenerating an already-committed parser) and must not abort the
#    script (R83): the repoint below is exactly what a new machine needs.
git add "$GRAMMAR"
if ! git diff --cached --quiet; then
  git commit -m 'regenerated tree-sitter-luna'
else
  echo "grammar unchanged: nothing to commit"
fi
git push

rev="$(git rev-parse HEAD)"
url="$(git remote get-url origin | sed -E 's#^git@([^:]+):#https://\1/#; s#\.git$##')"

# 2) Reconcile Zed's clone cache with the URL (R73): the clone in
#    $EXT/grammars is the LIVE grammar and must survive routine publishes,
#    but a clone from a DIFFERENT url blocks reinstall. Clear only on change.
clone="$EXT/grammars/luna"
if [ -d "$clone" ]; then
  old_url="$(git -C "$clone" remote get-url origin 2>/dev/null || echo '')"
  if [ "$old_url" != "$url" ]; then
    echo "grammar clone points at '$old_url', repointing to '$url': clearing cache"
    rm -rf "$EXT/grammars"
  fi
fi

# 3) extension.toml is GENERATED (only this script writes it).
cat > "$EXT/extension.toml" <<TOML
id = "luna"
name = "Luna"
version = "0.0.1"
schema_version = 1
authors = ["Luna spec"]
description = "Syntax highlighting for the Luna programming language."

# GENERATED by tooling/publish-grammar.sh: do not edit or copy by hand.

[grammars.luna]
repository = "$url"
rev = "$rev"
path = "$GRAMMAR"
TOML

# 4) Commit the repoint (if it changed; already-current is fine) and push.
git add "$EXT"
if ! git diff --cached --quiet; then
  git commit -m 'point zed-luna at regenerated grammar'
else
  echo "extension.toml already current: nothing to commit"
fi
git push

echo
echo "grammar rev: $rev"
echo "repository:  $url (path: $GRAMMAR)"
echo "Now in Zed: 'zed: reload extensions' (or 'zed: install dev extension' first time)."
